services:
  node:
    build:
      context: ./node/
      dockerfile: Dockerfile
    container_name: Node
    hostname: Node
    image: nodetono:release
    working_dir: /app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      - /media/local/Node/app:/app
    ports:
      - 80:8080
    command: node  /app/StartServer.js
